name: pick_my_parcel_customer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  steps_indicator: ^1.3.0
  intl: ^0.17.0
  calendar_date_picker2: ^0.1.7
  percent_indicator: ^4.2.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.4
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  provider: ^6.0.3
  firebase_storage: ^10.3.2
  http: ^0.13.5
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Montserrat SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf

    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Regular.ttf

    - family: PT Sans
      fonts:
        - asset: fonts/PTSans-Regular.ttf

    - family: Prompt SemiBold
      fonts:
        - asset: fonts/Prompt-SemiBold.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

    - family: Antonio
      fonts:
        - asset: fonts/Antonio-Regular.ttf